name: First Workflow 

on: 
  push:
    branches:
      - main

jobs:
  exapmles-job:
    runs-on: ubuntu-latest
    steps:
      - name : print a welcom message 
        run :  echo "welcome to our first project workflow!"
